djadmin_config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

### add import for django debug toolbar
from djadmin_config.settings import IS_DEVELOPMENT
from djadmin_config.settings import IS_USING_DJDT

from djadmin_config.settings import EXPORT_FILES_URL
from djadmin_config.settings import EXPORT_FILES_ROOT

from django.conf.urls.static import static

### uncomment when using DJDT
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('', include('djapp.import_export.urls', namespace='app_import_export')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(EXPORT_FILES_URL, document_root=EXPORT_FILES_ROOT)


if IS_DEVELOPMENT:
    if IS_USING_DJDT:
        '''
        '''
        ### uncomment when using DJDT
        urlpatterns += debug_toolbar_urls()

### change title words in django admin pages
admin.site.site_header = "Import Export Administration"
admin.site.site_title = "Import Export Admin Portal"
admin.site.index_title = "Welcome to Import Export Portal"

djapp/import_export/urls.py
## must add this file for every new django app with endpoints

from django.urls import path
from . import views

app_name = 'app_import_export'

urlpatterns = [
    path('', views.func_index, name='djep_index'),
    path('import/', views.func_import, name='djep_import'),
    path('clean_data/', views.func_clean_data, name='djep_clean_data'),
    path('import_data/', views.func_import_data, name='djep_import_data'),
    path('delete_data/', views.func_delete_data, name='djep_delete_data'),
    path('export/', views.func_export, name='djep_export'),
    path('export_data/', views.func_export_data, name='djep_export_data'),
]

templates/partials/_delete_form_modal.html
<!-- delete modal -->
<div
  class="modal fade"
  id="confirmDeleteFormModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="confirmDeleteFormModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmDeleteFormModalLabel">
          Confirm Deletion
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Cancel
        </button>
        <form action="#" method="post" id="confirmDeleteFormForm">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- end delete modal -->

templates/partials/_djmsg.html
<!-- display messages -->
<!-- for displaying alert messages in some html such as register and login -->
{% if messages %}
<!-- prettier-ignore -->
{% for message in messages %}
<div class="container text-center" id="djmessage{{ forloop.counter }}">
  <div
    class="alert alert-{{ message.tags }} alert-dismissible text-center"
    role="alert"
  >
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>
      <!-- prettier-ignore -->
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        Error:
      {% else %}
        {{ message.tags | title }}
      {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %}
<!-- prettier-ignore -->
{% endif %}
<!-- end display messages -->

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> Import Export
</footer>

templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-sm navbar-dark bg-primary sticky-top">
  <div class="container">
    <a class="navbar-brand" href={% url 'app_import_export:djep_index' %}>
      <img src={% static "img/logo.png" %} class="logo" alt="" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <!-- Home nav link -->
        <li 
          {% if '/' == request.path or '/index' == request.path %} 
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <!-- <a class="nav-link" href="index.html">Home</a> -->
          <a class="nav-link" href={% url 'app_import_export:djep_index' %}>
            <i class="fas fa-home"></i>&nbsp;Home</a>
        </li>
        <!-- Import nav link -->
        <li 
          {% if 'import' in request.path %} 
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <!-- <a class="nav-link" href="about.html">About</a> -->
          <a class="nav-link" href={% url 'app_import_export:djep_import' %}>
            <i class="fas fa-file-import"></i>&nbsp;Import</a>
        </li>
        <!-- Export nav link -->
        <li 
          {% if 'export' in request.path %} 
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href={% url 'app_import_export:djep_export' %}>
            <i class="fas fa-file-export"></i>&nbsp;Export</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-3">
          <a class="nav-link" href="/admin">
            <i class="fas fa-fingerprint"></i>&nbsp;Admin</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-1">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <i class="fas fa-phone"></i>&nbsp;(852)-555-6789
      </div>
      <div class="col-sm-6 text-center">
        <i class="fas fa-envelope-open"></i>&nbsp;contact@ImportExport.com
      </div>
      <div class="col-sm-3">
        <div class="social text-right">
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-pinterest"></i></a>
        </div>
      </div>
    </div>
  </div>
</section>