djadmin_config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

### add import for django debug toolbar
from djadmin_config.settings import IS_DEVELOPMENT
from djadmin_config.settings import IS_USING_DJDT

from djadmin_config.settings import EXPORT_FILES_URL
from djadmin_config.settings import EXPORT_FILES_ROOT

from django.conf.urls.static import static

### uncomment when using DJDT
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('', include('djapp.import_export.urls', namespace='app_import_export')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(EXPORT_FILES_URL, document_root=EXPORT_FILES_ROOT)


if IS_DEVELOPMENT:
    if IS_USING_DJDT:
        '''
        '''
        ### uncomment when using DJDT
        urlpatterns += debug_toolbar_urls()

### change title words in django admin pages
admin.site.site_header = "Import Export Administration"
admin.site.site_title = "Import Export Admin Portal"
admin.site.index_title = "Welcome to Import Export Portal"

djapp/import_export/urls.py
## must add this file for every new django app with endpoints

from django.urls import path
from . import views

app_name = 'app_import_export'

urlpatterns = [
    path('', views.func_index, name='djep_index'),
    path('import/', views.func_import, name='djep_import'),
    path('clean_data/', views.func_clean_data, name='djep_clean_data'),
    path('import_data/', views.func_import_data, name='djep_import_data'),
    path('delete_data/', views.func_delete_data, name='djep_delete_data'),
    path('export/', views.func_export, name='djep_export'),
    path('export_data/', views.func_export_data, name='djep_export_data'),
]

templates/tpl_import_export/export.html
{% extends 'base.html' %}

<!-- after using the collectstatic command -->
{% load static %}

<!-- load humanize -->
{% load humanize %}

<!-- webpage tab title -->
{% block title %}Export{% endblock %}

<!-- main content -->
{% block content %}

<div class="container" style="height: 218px" id="block_content_div_id">

<!-- djmsg -->
{% include 'partials/_djmsg.html'%}

<div class="container text-center mb-2"></div>

<div class="container text-center">
  <form action="{% url 'app_import_export:djep_export_data' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary mb-3">Export Data</button>
  </form>

  {% if export_record_count %}
    {% if json_filename_url %}
    <a href="{{ json_filename_url }}">JSON File</a>
    {% endif %}
    <br><br>
    {% if csv_filename_url %}
    <a href="{{ csv_filename_url }}">CSV File</a>
    {% endif %}
  {% endif %}
</div>

</div>

<!-- end block content -->
{% endblock %}

templates/tpl_import_export/import.html
{% extends 'base.html' %}

<!-- after using the collectstatic command -->
{% load static %}

<!-- load humanize -->
{% load humanize %}

<!-- webpage tab title -->
{% block title %}Import{% endblock %}

<!-- main content -->
{% block content %}

<div class="container" style="height: 218px" id="block_content_div_id">
<!-- djmsg -->
{% include 'partials/_djmsg.html' %}

<div class="container text-center mb-2"></div>

<div class="container text-center">
<form action="{% url 'app_import_export:djep_clean_data' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-info mb-2">Clean Data</button>
</form>
</div>

<div class="container text-center">
<form action="{% url 'app_import_export:djep_import_data' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary mb-2">Import Data</button>
</form>
</div>

<!-- form moved to modal for delete data -->
<div class="text-center">
  <button
    class="btn btn-danger mb-2"
    data-url="{% url 'app_import_export:djep_delete_data' %}"
    data-toggle="modal"
    data-target="#confirmDeleteFormModal"
    data-id="0"
  >
    Delete Data
  </button>
</div>

</div>

<!-- end block content -->
{% endblock %}

templates/tpl_import_export/index.html
{% extends 'base.html' %}

<!-- after using the collectstatic command -->
{% load static %}

<!-- load humanize -->
{% load humanize %}

<!-- webpage tab title -->
{% block title %}Import Export{% endblock %}

<!-- main content -->
{% block content %}

<div class="container" style="height: 218px" id="block_content_div_id">
  <!-- djmsg -->
  {% include 'partials/_djmsg.html'%}


  <div class="container text-center mb-2"></div>

  <div class="container text-center">
  <h1>
    <a href="{% url 'app_import_export:djep_import' %}" style="text-decoration:none;"><i class="fas fa-file-import"></i>&nbsp;Import</a>
    &nbsp;  &nbsp; 
    <a href="{% url 'app_import_export:djep_export' %}" style="text-decoration:none;"><i class="fas fa-file-export"></i>&nbsp;Export</a>
  </h1>
  </div>

</div>

<!-- end block content -->
{% endblock %}